---
site_name: Future Frame Docs
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:

    # Palette toggle for automatic mode
    - media: (prefers-color-scheme)
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: black
      acccent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      acccent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.footer
  extra:
    homepage: https://futureframe.ai
    consent:
      title: Cookie consent
      description: >-
        We use cookies to recognize your repeated visits and preferences, as well
        as to measure the effectiveness of our documentation and whether users
        find what they're searching for. With your consent, you're helping us to
        make our documentation better.
  favicon: assets/favicon.ico
  logo: assets/logo.png
plugins:
  - offline
  - tags
  - blog
  - privacy
  - mkdocstrings
  - autorefs
  - gen-files:
      scripts:
        - scripts/gen_ref_pages.py
repo_url: https://github.com/futureframeai/futureframe
